window.PRODUCTS = [
  {"id":"cb3142","name":"Пароочисник Crownberg CB-3142 9-в-1","short":"Швидке прибирання без зайвого тертя","price":999,"oldPrice":1199,"category":"cleaning","badge":"Хіт","emoji":"♨️","description":"Компактний пароочисник для кухні, плитки, сантехніки та важкодоступних місць.","features":["9 насадок","Пара для складних забруднень","Для кухні та ванної"],"source":"https://www.websklad.biz.ua/?paged=5&product_cat=tovary-dlya-doma-i-sada"},
  {"id":"nicer-dicer","name":"Овочерізка Nicer Dicer Plus","short":"Рівні шматочки за кілька секунд","price":399,"oldPrice":499,"category":"kitchen","badge":"Хіт","emoji":"🥗","description":"Мультифункціональна овочерізка з контейнером для швидкої підготовки продуктів.","features":["Швидка нарізка","Кілька насадок","Контейнер у комплекті"],"source":"https://www.websklad.biz.ua/?product=terka-nicer-dicer-plus"},
  {"id":"astronaut","name":"Проектор-нічник «Астронавт» 8 режимів","short":"Перетвори кімнату на галактику","price":549,"oldPrice":699,"category":"atmosphere","badge":"WOW","emoji":"🌌","description":"Проектор зоряного неба з пультом та кількома режимами підсвічування.","features":["8 режимів","Пульт керування","Яскравий візуальний ефект"],"source":"https://www.websklad.biz.ua/?product=nochnik-proektor-astronavt-zvezdnogo-neba-i-galaktiki-kosmonavt-8-rezhimov-s-pultom-du"},
  {"id":"car-vacuum","name":"Автопилосос Car Vacuum Cleaner","short":"Крихти та пил у салоні — за хвилини","price":399,"oldPrice":499,"category":"auto","badge":"Тест","emoji":"🚗","description":"Компактний автомобільний пилосос для швидкого прибирання салону.","features":["Компактний корпус","Для крихт та пилу","Зручно зберігати в авто"],"source":"https://www.websklad.biz.ua/?product=pylesos-dlya-avto-car-vacum-cleaner"},
  {"id":"gemei","name":"Машинка від ковтунців Gemei GM-231","short":"Повертає речам охайний вигляд","price":299,"oldPrice":379,"category":"cleaning","badge":"До/Після","emoji":"🧥","description":"Машинка для видалення ковтунців з одягу, пледів та домашнього текстилю.","features":["Помітний ефект до/після","Для одягу і текстилю","Компактний формат"],"source":"https://www.websklad.biz.ua/?product_tag=ot-katyshkov"},
  {"id":"spice-organizer","name":"Органайзер для 18 спецій","short":"Порядок на кухні в одному русі","price":899,"oldPrice":1099,"category":"kitchen","badge":"Порядок","emoji":"🧂","description":"Обертовий органайзер з 18 ємностями для спецій та приправ.","features":["18 ємностей","Обертається на 360°","Економить місце"],"source":"https://www.websklad.biz.ua/?product_tag=izmelchiteli-specij"},
  {"id":"vacuum-sealer","name":"Вакууматор Vacuum Sealer LP-11","short":"Менше повітря — компактніше зберігання","price":499,"oldPrice":599,"category":"kitchen","badge":"Практично","emoji":"🥩","description":"Компактний вакуумний пакувальник для продуктів.","features":["Відкачує повітря","Компактне зберігання","Дві кнопки керування"],"source":"https://www.websklad.biz.ua/?product=vakuumnyj-upakovshhik-vacuum-sealer-lp-11-s-novaya-model-dve-knopki"},
  {"id":"silicone-gloves","name":"Силіконові рукавички-щітки","short":"Зручний додаток до прибирання","price":179,"oldPrice":229,"category":"cleaning","badge":"Додай до замовлення","emoji":"🧤","description":"Силіконові рукавички з щетинками для миття посуду та поверхонь.","features":["Щетинки на долонях","Легко мити","Зручно як допродаж"],"source":"https://www.websklad.biz.ua/?product_tag=shvabry-shhetki"}
];
